// Static image map — pre-built at build time, no runtime API calls or fs writes.
// Generated by: npm run build-image-map
import imageMap from "@/data/image-map.json";

type ImageMap = Record<string, string>;
const map = imageMap as ImageMap;

/**
 * Look up image URL by product ID or composite key (code|type|series).
 * Returns undefined if no image found (CardImage will show gradient fallback).
 */
export function getImageUrl(key: string): string | undefined {
  return map[key];
}
