// Static image map — pre-built at build time, with pokemontcg.io fallback for live-only products.
// Generated by: npm run build-image-map
import imageMap from "@/data/image-map.json";

type ImageMap = Record<string, string>;
const map = imageMap as ImageMap;

const POKEMON_TCG_API = "https://api.pokemontcg.io/v2";
const runtimeCache = new Map<string, string | null>();

// Set code → pokemontcg.io set ID mapping
const SET_MAP: Record<string, string> = {
  SVI: "sv1",       // Scarlet & Violet
  PAL: "sv2",       // Paldea Evolved
  OBF: "sv3",       // Obsidian Flames
  MEW: "sv3pt5",    // Pokémon 151
  PAR: "sv4",       // Paradox Rift
  PAF: "sv4pt5",    // Paldean Fates
  TEF: "sv5",       // Temporal Forces
  TWM: "sv6",       // Twilight Masquerade
  SCR: "sv7",       // Stellar Crown
  SSP: "sv8",       // Surging Sparks
  PRE: "sv8pt5",    // Prismatic Evolutions
  JTG: "sv9",       // Journey Together
  DRI: "sv10",      // Destined Rivals
  MEG: "me1",       // Mega Evolution
  ASC: "me2pt5",    // Ascended Heroes
  POR: "me3",       // Perfect Order
  PFL: "me2",       // Phantasmal Flames
  SFA: "sv7pt5",    // Shrouded Fable
  BLK: "zsv10pt5",  // Black Bolt
  WHT: "rsv10pt5",  // White Flare
  PEL: "sv4pt5gg",  // Paldean Fates Galarian Gallery
  SVE: "sv1pt5",    // Scarlet & Violet Energies
  SVP: "svp",       // Scarlet & Violet Promos
};

function parseSeries(series: string): { setCode: string; cardNumber: string } | null {
  const s = series.trim();
  if (!s) return null;
  const match = s.match(/^(.+?)\s+(\d+)\//i);
  if (match) {
    const code = match[1].trim().toUpperCase().replace(/\s+(EN|GG|TG)$/i, "");
    return { setCode: code, cardNumber: match[2] };
  }
  return null;
}

/**
 * Build a direct pokemontcg.io image URL from set ID + card number.
 */
function buildImageUrl(setId: string, cardNumber: string): string {
  return `https://images.pokemontcg.io/${setId}/${cardNumber}_hires.png`;
}

/**
 * Look up image URL by product ID or composite key (code|type|series).
 */
export function getImageUrl(key: string, productName?: string): string | undefined {
  const cached = map[key];
  if (cached) return cached;

  if (runtimeCache.has(key)) {
    return runtimeCache.get(key) || undefined;
  }

  return undefined;
}

/**
 * Async: look up image, falling back to pokemontcg.io API if not cached.
 * Call this for live products that might not be in the pre-built map.
 */
export async function resolveImageUrl(
  key: string,
  productName: string
): Promise<string | undefined> {
  // Check static map first
  const cached = map[key];
  if (cached) return cached;

  // Check runtime cache
  if (runtimeCache.has(key)) {
    return runtimeCache.get(key) || undefined;
  }

  // Try to extract composite key parts for direct URL construction
  // Key format: "code|type|series" e.g. "PO-P-01|holo|MEG 054/132"
  const parts = key.split("|");
  if (parts.length >= 3) {
    const seriesPart = parts.slice(2).join("|");
    const parsed = parseSeries(seriesPart);
    if (parsed) {
      const setId = SET_MAP[parsed.setCode];
      if (setId) {
        const url = buildImageUrl(setId, parsed.cardNumber);
        runtimeCache.set(key, url);
        return url;
      }
    }
  }

  // Fallback: search pokemontcg.io API by name
  try {
    const res = await fetch(
      `${POKEMON_TCG_API}/cards?q=name:"${encodeURIComponent(productName)}"&pageSize=5`
    );
    if (res.ok) {
      const data = await res.json();
      const cards = data.data;
      if (Array.isArray(cards) && cards.length > 0) {
        const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");
        const normName = norm(productName);
        const match =
          cards.find((c: any) => norm(c.name || "") === normName) ||
          cards.find((c: any) => {
            const cn = norm(c.name || "");
            return cn.includes(normName) || normName.includes(cn);
          });
        if (match && match.images?.large) {
          runtimeCache.set(key, match.images.large);
          return match.images.large;
        }
      }
    }
  } catch {
    // pokemontcg.io lookup failed
  }

  runtimeCache.set(key, null);
  return undefined;
}
