// Static image map — pre-built at build time, with TCGdex fallback for live-only products.
// Generated by: npm run build-image-map
import imageMap from "@/data/image-map.json";

type ImageMap = Record<string, string>;
const map = imageMap as ImageMap;

const TCGDEX_BASE = "https://api.tcgdex.net/v2/en";
const runtimeCache = new Map<string, string | null>();

/**
 * Look up image URL by product ID or composite key (code|type|series).
 * Falls back to TCGdex name search for live-only products not in the pre-built map.
 */
export function getImageUrl(key: string, productName?: string): string | undefined {
  const cached = map[key];
  if (cached) return cached;

  // Try runtime cache (from previous TCGdex lookups this session)
  if (runtimeCache.has(key)) {
    return runtimeCache.get(key) || undefined;
  }

  // No image found — caller can trigger async lookup
  return undefined;
}

/**
 * Async: look up image, falling back to TCGdex name search if not cached.
 * Call this for live products that might not be in the pre-built map.
 */
export async function resolveImageUrl(
  key: string,
  productName: string
): Promise<string | undefined> {
  // Check static map first
  const cached = map[key];
  if (cached) return cached;

  // Check runtime cache
  if (runtimeCache.has(key)) {
    return runtimeCache.get(key) || undefined;
  }

  // Search TCGdex by name
  try {
    const res = await fetch(
      `${TCGDEX_BASE}/cards?name=${encodeURIComponent(productName)}&pagination:page=1&pagination:itemsPerPage=3`
    );
    if (res.ok) {
      const cards = await res.json();
      if (Array.isArray(cards)) {
        // Try exact match first, then includes match
        const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");
        const normName = norm(productName);
        const match =
          cards.find((c: any) => c.image && norm(c.name || "") === normName) ||
          cards.find((c: any) => c.image && (norm(c.name || "").includes(normName) || normName.includes(norm(c.name || ""))));
        if (match) {
          const url = match.image.includes("/high.png")
            ? match.image
            : match.image + "/high.png";
          runtimeCache.set(key, url);
          return url;
        }
      }
    }
  } catch {
    // TCGdex lookup failed
  }

  runtimeCache.set(key, null);
  return undefined;
}
